# Essential markdown linting rules

# Line length - disabled for technical content
MD013: false

# Heading style - consistent ATX style  
MD003:
  style: "atx"

# Unordered list style - consistent dashes
MD004:
  style: "dash"

# Trailing spaces - allow 2 for line breaks
MD009:
  br_spaces: 2

# Hard tabs - prefer spaces
MD010: true

# Line break at end of file
MD047: true

# Allow inline HTML for admonitions
MD033: false

# Allow duplicate heading content
MD024: false

# Allow bare URLs
MD034: false

# Disable first line heading rule (conflicts with YAML front-matter)
MD041: false

# Disable trailing punctuation in headers
MD026: false