# Simplified pre-commit configuration
repos:
  # Local validation hooks
  - repo: local
    hooks:
      # Basic YAML front-matter validation
      - id: validate-frontmatter
        name: Validate YAML front-matter
        entry: python scripts/validate-frontmatter.py
        language: python
        files: \.md$
        pass_filenames: false
        additional_dependencies: [pyyaml]
        
      # Basic internal link checking
      - id: check-internal-links
        name: Check internal links
        entry: python scripts/check-links.py
        language: python
        files: \.md$
        pass_filenames: false

  # Essential quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Check YAML syntax
      - id: check-yaml
        files: \.(yml|yaml)$
        
      # Trim trailing whitespace
      - id: trailing-whitespace
        files: \.md$
        
      # Ensure files end with newline
      - id: end-of-file-fixer
        files: \.md$

  # Basic markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--config', '.markdownlint.yaml']
        files: \.md$

# Configuration
default_stages: [commit]
fail_fast: false

# Exclude certain files
exclude: |
  (?x)(
    ^site/|
    ^\.git/
  )