# SystemCraft Content Standards Pre-commit Hooks
# Ensures all content meets quality and consistency standards before commit

repos:
  # Local hooks for SystemCraft-specific validation
  - repo: local
    hooks:
      # Validate YAML front-matter compliance
      - id: validate-frontmatter
        name: Validate YAML front-matter
        entry: python scripts/validate-frontmatter.py
        language: python
        files: \.md$
        pass_filenames: false
        additional_dependencies: [pyyaml]
        
      # Check internal link integrity
      - id: check-internal-links
        name: Validate internal links
        entry: python scripts/check-links.py
        language: python
        files: \.md$
        pass_filenames: false
        
      # Validate content standards compliance
      - id: validate-content-standards
        name: Check content standards compliance
        entry: python scripts/validate-content.py
        language: python
        files: \.md$
        pass_filenames: false
        additional_dependencies: [markdown, beautifulsoup4]

  # Standard formatting and quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Check for merge conflicts
      - id: check-merge-conflict
      
      # Check YAML syntax
      - id: check-yaml
        files: \.(yml|yaml)$
        
      # Check JSON syntax
      - id: check-json
        
      # Trim trailing whitespace
      - id: trailing-whitespace
        files: \.md$
        
      # Ensure files end with newline
      - id: end-of-file-fixer
        files: \.md$
        
      # Check for large files
      - id: check-added-large-files
        args: ['--maxkb=1000']
        
      # Check case conflicts
      - id: check-case-conflict

  # Markdown formatting and linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--config', '.markdownlint.yaml']
        files: \.md$

  # Python code formatting (for scripts)
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        files: ^scripts/.*\.py$
        
  # Python import sorting (for scripts)
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^scripts/.*\.py$
        args: ["--profile", "black"]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(yml|yaml)$
        args: ['--write']

# Configuration
default_stages: [commit]
fail_fast: false

# Exclude certain files from all hooks
exclude: |
  (?x)(
    ^site/|
    ^\.git/|
    README\.md$|
    CHANGELOG\.md$
  )