site_name: Amazon L6/L7 Engineering Manager Interview Prep
site_url: https://deepaucksharma.github.io/SystemCraft/
site_description: Complete preparation guide for Amazon L6/L7 Engineering Manager Technical Interviews
site_author: SystemCraft

repo_url: https://github.com/deepaucksharma/SystemCraft
repo_name: deepaucksharma/SystemCraft
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 SystemCraft

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # Enhanced Navigation
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # Enhanced Table of Contents
    - toc.follow
    - toc.integrate
    # Enhanced Search
    - search.suggest
    - search.highlight
    - search.share
    # Content Enhancements
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    # Header enhancements
    - header.autohide
    - announce.dismiss

plugins:
  # Core functionality
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags
  
  # Visual enhancements
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
  
  # Content organization (temporarily disabled - need to install)
  # - minify:
  #     minify_html: true
  #     minify_js: true
  #     minify_css: true
  #     htmlmin_opts:
  #         remove_comments: true
  #     cache_safe: true
  
  # Analytics and tracking (temporarily disabled - need to install)
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago
  #     timezone: UTC
  #     locale: en
  #     fallback_to_build_date: false
  #     enabled: true
  
  # Enhanced content features (commented out - need installation)
  # - awesome-pages
  # - include-markdown

markdown_extensions:
  # Core markdown
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
      toc_depth: 4
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - fenced_code
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - abbr
  
  # Enhanced content features
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vega-lite
          class: vegalite
          format: !!python/name:pymdownx.superfences.fence_div_format
  
  # Code enhancements
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  
  # Content organization
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  
  # Enhanced formatting
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.smartsymbols
  
  # Mathematical content
  - pymdownx.arithmatex:
      generic: true
  
  # Advanced features
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all

extra_css:
  - stylesheets/extra.css
  - stylesheets/decision-trees.css
  - stylesheets/learning-paths.css
  - stylesheets/mobile-enhancements.css
  - stylesheets/accessibility.css
  - stylesheets/interactive-elements.css
  - stylesheets/visual-learning.css

extra_javascript:
  # Security utilities must load first
  - javascripts/security-utils.js
  - javascripts/mathjax.js
  - javascripts/decision-trees.js
  - javascripts/learning-progress.js
  - javascripts/search-enhancements.js
  - javascripts/keyboard-shortcuts.js
  - javascripts/personalization.js
  - javascripts/mobile-optimizations.js
  - javascripts/progressive-disclosure.js
  - javascripts/interactive-diagrams.js
  - javascripts/onboarding.js
  - javascripts/mock-interview-system.js
  - javascripts/video-practice.js
  - javascripts/collaborative-coding.js
  - javascripts/analytics-dashboard.js
  - javascripts/visual-learning.js
  - javascripts/spaced-repetition.js
  # DOMPurify for XSS protection - with SRI hash
  - https://cdn.jsdelivr.net/npm/dompurify@3.0.5/dist/purify.min.js
  # External libraries for advanced features - with SRI hashes when possible
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  # Monaco Editor for collaborative coding
  - https://cdn.jsdelivr.net/npm/monaco-editor@latest/min/vs/loader.js
  # Chart.js for analytics dashboard
  - https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.js


nav:
  - Home: index.md
  
  # 🎯 START HERE - Initial orientation and assessment
  - 🎯 Start Here:
    - Quick Assessment: self-assessment-quiz.md
    - Getting Started Guide: getting-started.md
    - Interview Success Mindset: fundamentals/interview-success-mindset.md
    - Foundational Mindset: foundational-mindset/index.md
    - L6 vs L7 Decision Guide: fundamentals/l6-vs-l7.md
    - Interview Process Overview: fundamentals/interview-process.md
    - Written Assessment Guide: interview-process/written-assessment-guide.md
    - Work Simulation Assessment: interview-process/work-simulation-assessment.md
    - Behavioral Multiple Choice: interview-process/behavioral-multiple-choice.md
    - Interview Mechanics: interview-mechanics/index.md
  
  # 📚 CORE PREPARATION - Main interview components  
  - 📚 Core Preparation:
    - Behavioral Leadership:
      - Overview & Strategy: behavioral/index.md
      - STAR Framework Mastery: behavioral/star-framework.md
      - STAR Story Bank Template: behavioral/star-story-bank-template.md
      - Leadership Principles Deep Dive: fundamentals/leadership-principles.md
      - L6 Behavioral Excellence: behavioral/l6-behavioral-mastery.md
      - L7 Behavioral Excellence: behavioral/l7-behavioral-mastery.md
      - L6 vs L7 Differentiation: behavioral/l6-vs-l7-differentiation.md
      - Impact Quantification: behavioral/impact-quantification.md
      - Bar Raiser Preparation: behavioral/bar-raiser-mastery.md
      - Bar Raiser Questions: behavioral/bar-raiser-questions.md
      - Bar Raiser Recovery: behavioral/bar-raiser-recovery.md
      - L6 Scenarios: behavioral/l6-scenarios.md
      - L7 Scenarios: behavioral/l7-scenarios.md
      - RTO Leadership Scenarios: behavioral/rto-leadership-scenarios.md
      - Climate Sustainability Leadership: behavioral/climate-sustainability-leadership.md
      - Neurodiversity Management: behavioral/neurodiversity-management.md
      - AI Ethics Leadership: behavioral/ai-ethics-leadership.md
      - DEI Leadership: behavioral/dei-leadership.md
      - Decision Making Framework: behavioral/decision-making.md
      - Missing Leadership Principles: behavioral/missing-leadership-principles.md
      - Advanced Psychological Preparation: behavioral/advanced-psychological-preparation.md
      - Bar Raiser Insider Guide: behavioral/bar-raiser-insider-guide.md
      - Data-Driven Answer Optimization: behavioral/data-driven-answer-optimization.md
    - System Design Mastery:
      - Overview & Strategy: system-design/index.md
      - Fundamentals: system-design/fundamentals.md
      - Advanced Distributed Systems: system-design/advanced-distributed-systems.md
      - Performance Engineering: system-design/performance-engineering.md
      - Database Architecture: system-design/database-architecture.md
      - Security Architecture: system-design/security-architecture.md
      - Scale & Architecture: system-design/scale-architecture.md
      - AWS Services: system-design/aws-services.md
      - Well-Architected Framework: system-design/well-architected.md
      - Generative AI Systems: system-design/generative-ai-systems.md
      - ML Systems Design: system-design/ml-systems-design.md
      - ML Design Problems: system-design/ml-design-problems.md
      - Amazon Scale Problems: system-design/amazon-scale-problems.md
      - L6 Design Problems: system-design/l6-problems.md
      - L7 Design Problems: system-design/l7-problems.md
      - Case Studies: system-design/case-studies.md
    - Technical Coding Excellence:
      - Overview & Strategy: coding/index.md
      - Data Structures: coding/data-structures.md
      - Algorithms: coding/algorithms.md
      - Advanced Graph Algorithms: coding/advanced-graph-algorithms.md
      - System-Scale Algorithms: coding/system-scale-algorithms.md
      - String Algorithms: coding/string-algorithms.md
      - Problem Patterns: coding/patterns.md
      - Amazon Top 100 Problems: coding/amazon-top-100.md
      - Mock Coding Problems: coding/mock-problems.md
  
  # 📈 STUDY PLANS - Time-based preparation paths
  - 📈 Study Plans:
    - Quick Reference (1-2 weeks): quick-reference.md
    - Intensive Prep (6-8 weeks): practice/6-week-plan.md
    - Comprehensive Plan (12+ weeks): practice/12-week-plan.md
    - Complete Study Plan (6 months): study-plan.md
    - Visual Learning Guide: learning/visual-learning-guide.md
    - Progress Tracking System: practice/comprehensive-progress-system.md
    - Self-Assessment Tools: practice/self-assessment.md
    - Competency Checkpoints: practice/competency-checkpoints.md
    - Gap Analysis Framework: practice/diagnostic-gap-analysis.md
  
  # 🎭 SPECIALIZED TRACKS - Targeted preparation paths
  - 🎭 Specialized Tracks:
    - Level-Specific Playbooks:
      - L6/L7 Success Formulas: level-playbooks/index.md
      - Technical Competencies: fundamentals/technical-competencies.md
    - Team-Specific Preparation:
      - Team Comparison Guide: team-specific/team-comparison.md
      - Team Fit Assessment: team-specific/team-fit-guide.md
      - AWS Track: team-specific/aws-track.md
      - Retail Track: team-specific/retail-track.md
      - Alexa Track: team-specific/alexa-track.md
      - Prime Video Track: team-specific/prime-video-track.md
      - Ads Track: team-specific/ads-track.md
      - Logistics Track: team-specific/logistics-track.md
      - FinTech Track: team-specific/fintech-track.md
    - Deep Technical Knowledge:
      - Distributed Systems: deep-dives/distributed-systems.md
      - AI/ML Leadership: deep-dives/ai-ml-leadership.md
      - Performance & Scale: deep-dives/performance-scale.md
      - Consistency Models: deep-dives/consistency-models.md
      - Security Deep Dive: deep-dives/security.md
      - Incident Response: deep-dives/incident-response.md
    - Latest Updates:
      - 2025 Interview Considerations: 2025-considerations/index.md
  
  # 🚀 PRACTICE & POLISH - Active preparation and refinement
  - 🚀 Practice & Polish:
    - Mock Interview System: features/mock-interview-guide.md
    - Mock Interview Practice: practice/mock-interviews.md
    - Video Practice Platform: practice/video-practice.md
    - Collaborative Coding: practice/collaborative-coding.md
    - Interactive Features: features/interactive-features.md
    - Analytics Dashboard: interactive/analytics-dashboard.md
    - Progress Dashboard: practice/progress-dashboard.md
    - Skill Assessment Tools: practice/skill-assessment.md
  
  # 📖 RESOURCES & SUPPORT - Templates, examples, and guidance
  - 📖 Resources & Support:
    - Portfolio & Career Development:
      - Portfolio Overview: portfolio/index.md
      - L6 Industry Portfolios: portfolio/l6-industry-portfolios.md
      - L7 Strategic Portfolios: portfolio/l7-strategic-portfolios.md
      - Business Impact Calculation: portfolio/business-impact-calculation.md
      - Technology Evaluation Frameworks: portfolio/technology-evaluation-frameworks.md
      - Risk Assessment Templates: portfolio/risk-assessment-templates.md
      - Technical Portfolio: portfolio/technical-portfolio.md
    - Templates & Downloads:
      - Downloads & Resources: downloads/index.md
    - Community & Support:
      - FAQ: fundamentals/faq.md
      - Real Interview Experiences: experiences/index.md
      - Candidate Success Stories: experiences/success-templates.md
      - Technical Examples: experiences/technical-examples.md
      - Timeline Examples: experiences/timeline-examples.md
      - Question Database: experiences/question-database.md
    - Compensation & Negotiation:
      - Compensation Guide: fundamentals/compensation.md
      - Negotiation Strategies: compensation/negotiation-guide.md
      - Negotiation Masterclass: compensation/negotiation-masterclass.md