site_name: Amazon L6/L7 Engineering Manager Interview Prep
site_url: https://deepaucksharma.github.io/SystemCraft/
site_description: Complete preparation guide for Amazon L6/L7 Engineering Manager Technical Interviews
site_author: SystemCraft

repo_url: https://github.com/deepaucksharma/SystemCraft
repo_name: deepaucksharma/SystemCraft
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 SystemCraft

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select

plugins:
  - search:
      lang: en
  - glightbox

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - fenced_code
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mtml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
    - Start Here: getting-started.md
    - Assessment & Placement: self-assessment-quiz.md
    - L6 vs L7 Guide: fundamentals/l6-vs-l7.md
    - Interview Process: fundamentals/interview-process.md
  - Study Plans:
    - Quick Start (2 weeks): quick-reference.md
    - Intensive (6 weeks): practice/6-week-plan.md
    - Comprehensive (12 weeks): practice/12-week-plan.md
    - Custom Planning: practice/weekly-plan.md
  - Behavioral Leadership:
    - Overview & Strategy: behavioral/index.md
    - STAR Framework: behavioral/star-framework.md
    - Leadership Principles: fundamentals/leadership-principles.md
    - L6 Scenarios: behavioral/l6-scenarios.md
    - L7 Scenarios: behavioral/l7-scenarios.md
    - Bar Raiser Prep: behavioral/bar-raiser.md
    - Decision Making: behavioral/decision-making.md
  - System Design:
    - Overview & Strategy: system-design/index.md
    - Fundamentals: system-design/fundamentals.md
    - Scale & Architecture: system-design/scale-architecture.md
    - AWS Services: system-design/aws-services.md
    - Well-Architected: system-design/well-architected.md
    - L6 Problems: system-design/l6-problems.md
    - L7 Problems: system-design/l7-problems.md
    - Case Studies: system-design/case-studies.md
  - Technical Coding:
    - Overview & Strategy: coding/index.md
    - Data Structures: coding/data-structures.md
    - Algorithms: coding/algorithms.md
    - Problem Patterns: coding/patterns.md
    - Amazon Top 100: coding/amazon-top-100.md
    - Mock Problems: coding/mock-problems.md
  - Deep Technical Knowledge:
    - Technical Competencies: fundamentals/technical-competencies.md
    - Distributed Systems: deep-dives/distributed-systems.md
    - Performance & Scale: deep-dives/performance-scale.md
    - Consistency Models: deep-dives/consistency-models.md
    - Security: deep-dives/security.md
    - Incident Response: deep-dives/incident-response.md
  - Portfolio & Examples:
    - Technical Portfolio: portfolio/technical-portfolio.md
    - Code Samples: portfolio/code-samples.md
    - Decision Records: portfolio/decision-records.md
    - Architecture Diagrams: portfolio/architecture-diagrams.md
  - Progress Tracking & Assessment:
    - Complete Progress System: practice/comprehensive-progress-system.md
    - Progress Tracking Framework: practice/progress-tracking-system.md
    - Competency Checkpoints: practice/competency-checkpoints.md
    - Learning Prerequisites: practice/learning-prerequisites.md
    - Diagnostic Gap Analysis: practice/diagnostic-gap-analysis.md
    - Adaptive Learning Framework: practice/adaptive-learning-framework.md
    - Self Assessment: practice/self-assessment.md
    - Weekly Planning: practice/weekly-plan.md
    - Mock Interview Guide: practice/mock-interviews.md
  - Quick Reference & Support:
    - Interview Day Checklist: quick-reference.md
    - FAQ: faq/index.md
    - Real Experiences: experiences/index.md
    - Compensation Guide: compensation/negotiation-guide.md
    - Resources & Downloads: downloads/index.md